spring:
  datasource:
    primary: #ITMS
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  #sqlserver
      #单数据源更改为url
      jdbc-url: jdbc:sqlserver://172.60.6.115;DatabaseName=ITMS
      username: sa
      password: lw2019.
    second:   #HRM
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  #sqlserver
      jdbc-url: jdbc:sqlserver://172.60.6.27;DatabaseName=HRM
      username: sa
      password: sa@!admin1
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  devtools:
    restart:
      enabled: true
      exclude: WEB/INF/**
      additional-paths: src/main/java
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
server:
  port: 8093